menu:
  Home: /
  Archives: /archives

widgets:
- search
- category
- tag

excerpt_link: more

twitter:
  username: medicorab
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: false

google_analytics:
rss:

comment_provider:
