menu:
  Home:
    link: /
    icon: fa-home
  Archives:
    link: /archives
    icon: fa-archive

widgets:
- search
- category
- tag

excerpt_link: more ...

twitter:
  username: medicorab
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid: ra-549341e47fef0807

fancybox: false

google_analytics: UA-19223409-1
rss:

comment_provider: